---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-azure-sc-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: mongodb-azure
  #storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: test-mongodb-azure-sc-pod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: mongodb-azure-sc-pvc 
